### PR TITLE
MRC-1657: Update docker build based on feedback

### PR DESCRIPTION
**Pull request by r-ash**
> ## Dockerfile
> 
>  
> 
> * We probably should depend on R version 4 now
> 
>  
> 
> * Best practice for apt installation is apparently:
> 
>  
> 
> ```
> RUN apt-get update && apt-get -y install --no-install-recommends \
>     <packages> \
>     && apt-get clean \
>     && rm -rf /var/lib/apt/lists/*
> ```
> 
>  
> 
> * The lines:
> 
>  
> 
> ```
> COPY docker/bin /usr/local/bin/
> RUN sed  -i'' '/mran.microsoft.com/d' /usr/local/lib/R/etc/Rprofile.site
> ```
> 
>  
> 
> have stopped working for us in the past - see vimc/orderly/docker/Dockerfile for an alternative approach where we just replace the whole Rprofile.site
> 
>  
> 
> * You do not need the last line installing traduire from remotes (and avoiding that will help with API-limits hit by remotes)
> 
>  
> 
> * I thought that we were dropping INLA?
> 
>  
> 
> * I have had mixed (i.e., low) success with RcppEigen compiling correctly in docker - it gets regularly killed due to running out of RAM in orderly container builds
> 
>  
> 
> ## Others
> 
>  
> 
> * Do you want the docker/clear_docker script? Do you use it?
> * The two conditionals in docker/common could be merged
> * The docker/test script looks wrong to me as you start it as a daemon (i.e., backgrounded). So the exit code will always be 0 - at the same time the container will eventually exit as there is no daemon process.
> * Can you please add an MIT licence as LICENSE.md or similar?

### CODE REVIEW

**Comment by r-ash** [comment]
> > ## Dockerfile
> > 
> > * We probably should depend on R version 4 now
> > * Best practice for apt installation is apparently:
> > 
> > ```
> > RUN apt-get update && apt-get -y install --no-install-recommends \
> >     <packages> \
> >     && apt-get clean \
> >     && rm -rf /var/lib/apt/lists/*
> > ```
> > 
> > 
> > 
> > * The lines:
> > 
> > ```
> > COPY docker/bin /usr/local/bin/
> > RUN sed  -i'' '/mran.microsoft.com/d' /usr/local/lib/R/etc/Rprofile.site
> > ```
> > 
> > 
> > have stopped working for us in the past - see vimc/orderly/docker/Dockerfile for an alternative approach where we just replace the whole Rprofile.site
> > 
> > * You do not need the last line installing traduire from remotes (and avoiding that will help with API-limits hit by remotes)
> > * I thought that we were dropping INLA?
> > * I have had mixed (i.e., low) success with RcppEigen compiling correctly in docker - it gets regularly killed due to running out of RAM in orderly container builds
> > 
> > ## Others
> > 
> > * Do you want the docker/clear_docker script? Do you use it?
> > * The two conditionals in docker/common could be merged
> > * The docker/test script looks wrong to me as you start it as a daemon (i.e., backgrounded). So the exit code will always be 0 - at the same time the container will eventually exit as there is no daemon process.
> > * Can you please add an MIT licence as LICENSE.md or similar?

I think all these changed except a couple have been made.

* Asked Jeff about RcppEigen, he thinks it is used by TMB so I have left it in. We could try and remove it and see if it works without it
* Left in the line `COPY docker/bin /usr/local/bin/` we still need this for making the install scripts available
* re the `docker/test` script, I've removed the `-d` flag. Mostly here I just want to test that I can bring up the container, unless there is something more useful I can test?

**Review by richfitz — CHANGES_REQUESTED** [review]
Can you please add the buildkite badge to the README please and configure buildkite to ping back on PRs?

**Comment by r-ash** [comment]
> Can you please add the buildkite badge to the README please and configure buildkite to ping back on PRs?

Thanks, added the badge. Buildkite is reporting back in the list of checks atm. Or you mean something else?

**Comment by richfitz** [comment]
Sorry I missed the pingback as I'd expected it to show a different looking list!

**Review by richfitz — APPROVED** [review]

**Pull request merged**
